# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# VALIDATE_ALL_CODEBASE: true

DEFAULT_BRANCH: master # Usually master or main

# all, none, or list of linter keys
APPLY_FIXES: none

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  - SPELL # Comment to enable checks of spelling mistakes

DISABLE_LINTERS:
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS
  - YAML_V8R

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false

# # Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true

EXCLUDED_DIRECTORIES:
  - .vscode

CPP_CPPLINT_FILTER_REGEX_EXCLUDE: "include/freebsd_fix.h"
C_CPPLINT_FILTER_REGEX_EXCLUDE: "include/freebsd_fix.h"
C_CPPLINT_DISABLE_ERRORS: true # TODO consider disabling this later
