---
services:
  samba-ad:
    image: nowsci/samba-domain:latest
    container_name: samba-ad.example.com
    privileged: true
    hostname: samba-ad.example.com
    environment:
      - DOMAIN=EXAMPLE.COM
      - DOMAIN_DC=dc=example,dc=com
      - DOMAIN_EMAIL=example.com
      - DOMAINPASS=YourStrongPassword123_
    dns:
      - 127.0.0.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "88:88/tcp"
      - "88:88/udp"
      - "135:135/tcp"
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "389:389/tcp"
      - "445:445/tcp"
      - "464:464/tcp"
      - "464:464/udp"
      - "636:636/tcp"
      - "3268:3268/tcp"
      - "3269:3269/tcp"
    volumes:
      - samba_data:/var/lib/samba  # Use Docker volume instead of host path
      - ./myshare:/srv/myshare
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - ./smb.conf:/etc/samba/smb.conf

    networks:
      samba_net:
        ipv4_address: 172.28.1.10

  samba-client:
    image: smblinux:latest
    container_name: samba-client
    environment:
      - N2OS_SMB_PASSWORD=YourStrongPassword123_
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    dns:
      - 172.28.1.10  # Point to the Samba AD DC
    networks:
      samba_net:
        ipv4_address: 172.28.1.11
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./krb5.conf:/etc/krb5.conf:ro

networks:
  samba_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/24

volumes:
  samba_data:
  myshare:
