name: Multi-platform build

on:
  push:
    branches: master
    tags: "*"
  workflow_dispatch:
  pull_request:

jobs:
  build-linux:
    uses: ./.github/workflows/linux.yml
    secrets: inherit
  build-freebsd:
    uses: ./.github/workflows/freebsd.yml
    secrets: inherit
  finalize:
    runs-on: ubuntu-22.04
    needs: [build-linux, build-freebsd]
    steps:
      - name: Download artifact - FreeBSD x86-64
        uses: actions/download-artifact@v3
        with:
          name: n2os_smb_client.bsd_x86-64
          path: bin/
      - name: Download artifact - FreeBSD arm64
        uses: actions/download-artifact@v3
        with:
          name: n2os_smb_client.bsd_arm64
          path: bin/
      - name: Download artifact - Linux x86-64
        uses: actions/download-artifact@v3
        with:
          name: n2os_smb_client.linux_x86-64
          path: bin/
      - name: Download artifact - Linux arm64
        uses: actions/download-artifact@v3
        with:
          name: n2os_smb_client.linux_arm64
          path: bin/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
        with:
          files: |
            bin/n2os_smb_client.bsd
            bin/n2os_smb_client.bsd_arm64
            bin/n2os_smb_client.linux
            bin/n2os_smb_client.linux_arm64
          fail_on_unmatched_files: true
          generate_release_notes: true
