name: FreeBSD build

on:
  # push: 
  workflow_dispatch: 
  pull_request: 

jobs:
  freebsdbuild:
    timeout-minutes: 30
    # runs-on: ubuntu-22.04
    runs-on: nws-self-hosted-xlarge
    name: Build on FreeBSD
    # env:
    #   MYTOKEN : ${{ secrets.MYTOKEN }}
    #   MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    # - name: Build in FreeBSD
    #   id: build
    #   uses: vmactions/freebsd-vm@v1
    #   with:
    #     # envs: 'MYTOKEN MYTOKEN2'
    #     usesh: true
    #     # sync: sshfs
    #     # mem: 2048
    #     release: '13.2'
    #     # prepare: |
    #     #   pkg install -y git
    #     #   git submodule update --init --recursive
    #     run: |
    #       ./build.bsd.sh
    - name: Cross Platform Action
      uses: cross-platform-actions/action@v0.21.1
      with:
        operating_system: freebsd
        version: '13.0'
        # shell: sh
        # shell: bash
        # sync_files: false
        run: |
          ./build.bsd.sh
    - name: Store executable
      uses: actions/upload-artifact@v3
      with:
        name: n2os_smb_client.bsd
        path: bin/n2os_smb_client.bsd
