name: FreeBSD build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  freebsdbuild:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    name: Build on FreeBSD
    strategy:
      matrix:
        arch: [x86-64, arm64]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cross Platform Action
        uses: cross-platform-actions/action@v0.21.1
        with:
          operating_system: freebsd
          version: "13.2"
          shell: bash
          sync_files: true
          architecture: ${{ matrix.arch }}
          run: |
            sudo pkg install -y cmake krb5 heimdal
            ./build.bsd.sh
      - name: Store executable
        uses: actions/upload-artifact@v4
        with:
          name: "n2os_smb_client.bsd_${{ matrix.arch }}"
          path: bin/n2os_smb_client.bsd*
