name: Linux build

on:
  # push: 
  workflow_dispatch: 
  pull_request: 

jobs:
  linuxbuild:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    name: Build on Linux
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Prepare environment
      run: |
        apt-get update
        apt-get install -y --no-install-recommends build-essential upx-ucl cmake libssl-dev libkrb5-dev
        ldconfig
    - name: Build
      run: |
        ./build.linux.sh
    - name: Store executable
      uses: actions/upload-artifact@v3
      with:
        name: n2os_smb_client.linux
        path: bin/n2os_smb_client.linux
